src/Entity/Appointment.php
<?php

namespace App\Entity;

use App\Repository\AppointmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AppointmentRepository::class)]
class Appointment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'appointments')]
    private ?Client $client = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $complaints = null;

    #[ORM\Column(nullable: true)]
    private ?int $status = null;


    #[ORM\ManyToOne]
    private ?Employee $manager = null;

    #[ORM\OneToMany(mappedBy: 'appointment', targetEntity: Job::class)]
    private Collection $jobs;

    #[ORM\ManyToOne(inversedBy: 'appointment', targetEntity: ClientCar::class)]
    #[ORM\JoinColumn(name: 'client_car_id', referencedColumnName: 'id')]
    private ?ClientCar $clientCar = null;

    #[ORM\ManyToMany(targetEntity: Part::class)]
    private Collection $parts;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
        $this->parts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(\DateTimeImmutable $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getComplaints(): ?string
    {
        return $this->complaints;
    }

    public function setComplaints(?string $complaints): self
    {
        $this->complaints = $complaints;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(?int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getManager(): ?Employee
    {
        return $this->manager;
    }

    public function setManager(?Employee $manager): self
    {
        $this->manager = $manager;

        return $this;
    }

    /**
     * @return Collection<int, Job>
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): self
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs->add($job);
            $job->setAppointment($this);
        }

        return $this;
    }

    public function removeJob(Job $job): self
    {
        if ($this->jobs->removeElement($job)) {
            // set the owning side to null (unless already changed)
            if ($job->getAppointment() === $this) {
                $job->setAppointment(null);
            }
        }

        return $this;
    }

    public function getClientName(): string
    {
        return $this->client.'';
    }
    public function getClientPhone(): string
    {
        return $this->client->getPhone();
    }

    public function getManagerName(): string
    {
        return $this->manager.'';
    }

    public function getFormattedDate(): string
    {
        return $this->getDate()->format('Y-m-d H:i');
    }

    public function getClientCar(): ?ClientCar
    {
        return $this->clientCar;
    }

    public function setClientCar(?ClientCar $clientCar): self
    {
        $this->clientCar = $clientCar;

        return $this;
    }

    /**
     * @return Collection<int, Part>
     */
    public function getParts(): Collection
    {
        return $this->parts;
    }

    public function addPart(Part $part): self
    {
        if (!$this->parts->contains($part)) {
            $this->parts->add($part);
        }

        return $this;
    }

    public function removePart(Part $part): self
    {
        $this->parts->removeElement($part);

        return $this;
    }
}

src/Form/AppointmentType.php
<?php

namespace App\Form;

use App\Entity\Appointment;
use App\Repository\ClientRepository;
use App\Repository\EmployeeRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AppointmentType extends AbstractType
{
    public function __construct(
        private ClientRepository $clientRepository,
        private EmployeeRepository $employeeRepository
    )
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $clients = $this->clientRepository->findAll();
        $employees = $this->employeeRepository->findAll();
        $clientCars = [];

        $builder
            ->add('date', DateTimeType::class, [
                'input' => 'datetime_immutable',
                'input_format' => 'Y-m-d H:i',
                'widget' => 'single_text',
                'data' => new \DateTimeImmutable(),

            ])
            ->add('complaints')
            ->add('client', ChoiceType::class, [
                'choices' => $clients,
                'choice_value' => 'id',
                'choice_label' => 'name',
            ])
            ->add('manager', ChoiceType::class, [
                'choices' => $employees,
                'choice_value' => 'id',
                'choice_label' => 'name',
            ])
            ->add('clientCar', ChoiceType::class, [
                'choices' => $clientCars,
                'choice_value' => 'id',
                'choice_label' => 'name',
            ])
            ->add('submit', SubmitType::class, ['label' => 'Добавить'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Appointment::class,
            'data' => new \DateTimeImmutable(),
        ]);
    }
}

src/Controller/AppointmentController.php
<?php

namespace App\Controller;

use App\Entity\Appointment;
use App\Form\AppointmentType;
use App\Helper\AppointmentStatusList;
use App\Repository\AppointmentRepository;
use App\Repository\ClientCarRepository;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AppointmentController extends AbstractController 
{
    public function __construct(
        private AppointmentRepository $appointmentRepo,
        private ClientRepository $clientRepository,
        private ClientCarRepository $clientCarRepository,
        private AppointmentStatusList $statusList,
    )
    {}

    #[Route('/appointment', name: 'appointment')]
    public function index(Request $request): Response
    {

        $appointments = $this->getAppointmentList();

        $form = $this->createForm(AppointmentType::class, new Appointment(), [
            'action' => '/add',
            'method' => 'POST'
        ]);



        return $this->render('appointment/base.html.twig', [
            'form' => $form->createView(),
            'form_label' => 'Создание новой записи',
            'appointments' => $appointments,
            'status_labels' => $this->statusList->getLabels()
        ]);
    }

    #[Route('/appointment/add', name: 'appointment.add', methods: ['POST'])]
    public function add(Request $request): Response
    {
        $form = $this->createForm(AppointmentType::class, new Appointment(), [
            'action' => 'add',
            'method' => 'POST',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() ) {
            $data = $form->getData();



            $clientCarId = null;
            foreach ($request->request->getIterator() as $i)
            {
                foreach ($i as $key => $value) {
                    if ($key == 'clientCar') {
                        $clientCarId = $value;
                        break;
                    }
                }
            }

            $clientCar = $this->clientCarRepository->findOneBy(['id' => $clientCarId]);

            if (!empty($clientCar)) {
                $data->setClientCar($clientCar);
            }

            $data->setStatus(AppointmentStatusList::SCHEDULED);

            $this->appointmentRepo->save($data, true);
        }

        return $this->redirectToRoute('appointment');
    }

    #[Route('/appointment/{id}/edit', name: 'appointment.edit',)]
    public function edit(Request $request, int $id): Response
    {

        return $this->render('appointment/edit.html.twig', [
            'id' => $id
        ]);
    }

    #[Route('/appointment/{id}/delete', name: 'appointment.delete',)]
    public function delete(Request $request, int $id): Response
    {
        // оно ничего не делает. надо имплементировать метод строчкой ниже.
        $this->appointmentRepo->deleteById($id);

        return $this->redirectToRoute('appointment');
    }

    public function getAppointmentList(): array
    {
        $appointmentList = $this->appointmentRepo->findNotDeleted();

        usort($appointmentList, function($a, $b) {
            return $a->getDate()->format('U') - $b->getDate()->format('U');
        });

        return $appointmentList;
    }
}

templates/appointment/base.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="container-fluid position-relative d-flex p-0">

        {% set dir = {'dir': 'appointment'} %}

        {% include 'sidebar.html.twig' with dir %}

        <!-- Content Start -->
        <div class="content">

            {% include 'navbar.html.twig' %}

            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        {{ form_start(form, {'action': 'appointment/add', 'method': 'POST'}) }}

                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">{{ form_label }}</h6>
                            <form>
                                <div class="mb-3">



                                    <select id="client_select" class="form-select mb-3" name="{{ field_name(form.client) }}" aria-label="Select example"
                                            data-client-id="{{ form.vars.value ? form.vars.value.id : '' }}">
                                        <option value="default" selected>{{ field_label(form.client) }}</option>

                                        {% for label, value in field_choices(form.client) %}
                                            <option value="{{ value }}">{{ label }}</option>
                                        {% endfor %}


                                    </select>

                                    <select id="client_car_select" class="form-select mb-3" name="{{ field_name(form.clientCar) }}" aria-label="Select example">
                                        <option value="default" selected>{{ field_label(form.clientCar) }}</option>
                                        {% for label, value in field_choices(form.clientCar) %}
                                            <option value="{{ value }}">{{ label }}</option>
                                        {% endfor %}
                                    </select>


                                    <div class="form-floating">
                                        <textarea class="form-control" id="appointment_complaints" name="appointment[complaints]" placeholder="Leave a comment here"
                                                  id="floatingTextarea" style="height: 150px;"></textarea>
                                        <label for="floatingTextarea">{{ form_label(form.complaints) }}</label>
                                    </div>

                                </div>
                                <div class="mb-3">
                                    {{ form_row(form.date) }}

                                </div>

                                <select class="form-select mb-3" name="{{ field_name(form.manager) }}" aria-label="Select example">
                                    <option value="default" selected>{{ field_label(form.manager) }}</option>
                                    {% for label, value in field_choices(form.manager) %}
                                        <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}

                                </select>
                                {{ form_row(form._token) }}

                                <button type="submit" class="btn btn-primary">Добавить</button>

                            </form>
                        </div>
{#                                {{ form_end() }}#}

                    </div>

                    {#Table#}

                    <div class="col-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Записи на обслуживание</h6>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Менеджер</th>
                                        <th scope="col">Клиент</th>
                                        <th scope="col">Телефон клиента</th>
                                        <th scope="col">Описание обращения</th>
                                        <th scope="col">Дата обращения</th>
                                        <th scope="col">Статус</th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for appointment in appointments %}
                                    <tr>
                                        <th scope="row">{{ appointment.id }}</th>
                                        <td>{{ appointment.managerName }}</td>
                                        <td>{{ appointment.clientName }}</td>
                                        <td>{{ appointment.clientPhone }}</td>
                                        <td>{{ appointment.complaints }}</td>
                                        <td>{{ appointment.date|date("H:i m/d/Y") }}</td>
                                        <td>{{ status_labels[appointment.status] }}</td>
                                        <td>
                                            <a  href="/appointment/{{ appointment.id }}/delete">
                                                <button type="button" class="btn btn-sm btn-link">Удалить</button>
                                            </a>
                                        </td>

                                    </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>

    </div>

    <script>
        $(document).ready(function() {

            $('#client_select').change(function() {
                var selectedOption = $(this).find('option:selected');
                var clientId = selectedOption.val();

                $(this).attr('data-client-id', clientId);
            });


            $('#client_select').change(function() { // Replace "your_form_client" with the actual field ID
                var clientId = $(this).val();

                $.ajax({
                    url: `/car/get?client_id=${clientId}`,
                    type: 'GET',
                    success: function(response) {
                        var carChoices = response.car_choices;

                        console.log(carChoices)

                        // Clear existing options
                        $('#client_car_select').empty();

                        // Populate the ClientCar field with retrieved choices
                        $.each(carChoices, function(index, choice) {
                            console.log(choice)
                            $('#client_car_select').append($('<option>').text(choice.name).val(choice.id));
                        });
                    }
                });
            });


        });
    </script>

{% endblock %}

templates/appointment/edit.html.twig
{% extends 'base.html.twig' %}
{% set dir = {'dir': 'appointment'} %}

{% block body %}

    <div class="container-fluid position-relative d-flex p-0">

        {% include 'sidebar.html.twig' with dir %}

        <!-- Content Start -->
        <div class="content">
            {% include 'navbar.html.twig' %}

            <div class="container-fluid pt-4 px-4">

                {{ id }}

            </div>

        </div>
    </div>


{% endblock %}

templates/appointment/form.html.twig
eee

{#{{ form_start(form, {'action': 'appointment_add', 'method': 'POST'}) }}#}
{#{{ form_widget(form) }}#}

                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">{{ form_label }}</h6>
                            <form>
                                <div class="mb-3">

                                    <select class="form-select mb-3" name="{{ field_name(form.client) }}" aria-label="Default select example">
                                        <option value="default" selected>{{ field_label(form.client) }}</option>

                                        {% for label, value in field_choices(form.client) %}
                                            <option value="{{ value }}">{{ label }}</option>
                                        {% endfor %}


                                    </select>

                                    <div class="form-floating">
                                        <textarea class="form-control" id="appointment[complaints]" placeholder="Leave a comment here"
                                              id="floatingTextarea" style="height: 150px;"></textarea>
                                        <label for="floatingTextarea">{{ form_label(form.complaints) }}</label>
                                    </div>

                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Дата и время</label><br>
                                            {{ form_row(form.date) }}
                                    <input type="date" id="appointment[date]"
                                           name="appointment-date" value="2023-06-12"
                                    >
                                    <input type="time" id="appointment[time]"
                                           name="appointment-time" value="19:30"
                                    >

                                </div>

                                <select class="form-select mb-3" name="appointment-manager" aria-label="Default select example">
                                    <option value="default" selected>Менеджер</option>
                                    {% for label, value in field_choices(form.manager) %}
                                        <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}

                                </select>

                                <button type="submit" class="btn btn-primary">Sign in</button>

                            </form>
                        </div>
{#                                {{ form_end() }}#}

templates/appointment/new.html.twig
{#{{ form_label(form.appointment, 'My Custom Task Label') }}#}
{#{{ form(form) }}#}
{{ form_start(form) }}

    {{ form_row(form.date) }}

{{ form_end(form) }}